default: &default
  adapter: mysql2
  encoding: utf8
  database: disluncho
  reconnect: false
  username: root
  password:
  socket: /tmp/mysql.sock
  pool: 5

development:
  database: disluncho_development
  <<: *default

test:
  database: disluncho_test
  <<: *default

production:
  database: disluncho_production
  <<: *default
